#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AgentTestPilot - Reporter Module
报告生成模块
"""

import os
import json
import time
from typing import Dict, List, Any
from abc import ABC, abstractmethod


class Reporter(ABC):
    """报告生成器抽象基类"""

    def __init__(self):
        self.default_filename = "report.txt"

    @abstractmethod
    def generate(self, data: Dict[str, Any], filepath: str):
        """生成报告"""
        pass


class JSONReporter(Reporter):
    """JSON格式报告生成器"""

    def __init__(self):
        super().__init__()
        self.default_filename = "report.json"

    def generate(self, data: Dict[str, Any], filepath: str):
        """生成JSON报告"""
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)


class MarkdownReporter(Reporter):
    """Markdown格式报告生成器"""

    def __init__(self):
        super().__init__()
        self.default_filename = "report.md"

    def generate(self, data: Dict[str, Any], filepath: str):
        """生成Markdown报告"""
        lines = []
        lines.append("# 🧪 AgentTestPilot Test Report")
        lines.append("")
        lines.append(f"**Generated:** {data.get('timestamp', 'N/A')}")
        lines.append(f"**Total Duration:** {data.get('total_duration', 0):.2f}s")
        lines.append("")

        # 汇总
        lines.append("## 📊 Summary")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Total Suites | {data.get('total_suites', 0)} |")
        lines.append(f"| Total Tests | {data.get('total_tests', 0)} |")
        lines.append(f"| ✅ Passed | {data.get('passed', 0)} |")
        lines.append(f"| ❌ Failed | {data.get('failed', 0)} |")
        lines.append(f"| ⚠️ Errors | {data.get('errors', 0)} |")
        lines.append(f"| ⏭️ Skipped | {data.get('skipped', 0)} |")
        lines.append(f"| 📈 Success Rate | {data.get('success_rate', 0) * 100:.1f}% |")
        lines.append("")

        # 套件详情
        lines.append("## 📁 Suite Details")
        lines.append("")

        for suite in data.get("suite_results", []):
            suite_name = suite.get("suite_name", "Unknown")
            total = suite.get("total_tests", 0)
            passed = suite.get("passed", 0)
            failed = suite.get("failed", 0)
            errors = suite.get("errors", 0)
            duration = suite.get("duration", 0)
            rate = suite.get("success_rate", 0) * 100

            status_icon = "✅" if rate == 100 else "❌" if failed > 0 else "⚠️"

            lines.append(f"### {status_icon} {suite_name}")
            lines.append("")
            lines.append(f"- **Tests:** {total} | **Passed:** {passed} | **Failed:** {failed} | **Errors:** {errors}")
            lines.append(f"- **Duration:** {duration:.2f}s | **Success Rate:** {rate:.1f}%")
            lines.append("")

            # 测试用例详情
            if suite.get("results"):
                lines.append("#### Test Cases")
                lines.append("")
                lines.append("| Test | Status | Duration | Score |")
                lines.append("|------|--------|----------|-------|")

                for result in suite["results"]:
                    test = result.get("test", {})
                    test_name = test.get("name", "Unknown")
                    test_result = result.get("result", {})
                    status = test_result.get("status", "unknown")
                    test_duration = test_result.get("duration", 0)
                    score = test_result.get("score", 0)

                    status_icon = {"passed": "✅", "failed": "❌", "error": "⚠️",
                                   "skipped": "⏭️", "running": "🔄"}.get(status, "❓")

                    lines.append(f"| {test_name} | {status_icon} {status} | {test_duration:.2f}s | {score * 100:.0f}% |")
                lines.append("")

        # 页脚
        lines.append("---")
        lines.append("")
        lines.append("*Generated by [AgentTestPilot](https://github.com/gitstq/AgentTestPilot) 🧪*")

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))


class HTMLReporter(Reporter):
    """HTML格式报告生成器"""

    def __init__(self):
        super().__init__()
        self.default_filename = "report.html"

    def generate(self, data: Dict[str, Any], filepath: str):
        """生成HTML报告"""
        html = self._build_html(data)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)

    def _build_html(self, data: Dict[str, Any]) -> str:
        """构建HTML内容"""
        total = data.get("total_tests", 0)
        passed = data.get("passed", 0)
        failed = data.get("failed", 0)
        errors = data.get("errors", 0)
        skipped = data.get("skipped", 0)
        rate = data.get("success_rate", 0) * 100

        # 计算颜色
        if rate >= 90:
            rate_color = "#28a745"
        elif rate >= 70:
            rate_color = "#ffc107"
        else:
            rate_color = "#dc3545"

        suites_html = ""
        for suite in data.get("suite_results", []):
            suite_rate = suite.get("success_rate", 0) * 100
            if suite_rate == 100:
                suite_status = "passed"
                suite_icon = "✅"
            elif suite.get("failed", 0) > 0:
                suite_status = "failed"
                suite_icon = "❌"
            else:
                suite_status = "error"
                suite_icon = "⚠️"

            tests_html = ""
            for result in suite.get("results", []):
                test = result.get("test", {})
                test_result = result.get("result", {})
                status = test_result.get("status", "unknown")
                status_class = status

                tests_html += f"""
                <tr class="{status_class}">
                    <td>{test.get('name', 'Unknown')}</td>
                    <td><span class="badge {status_class}">{status.upper()}</span></td>
                    <td>{test_result.get('duration', 0):.2f}s</td>
                    <td>{test_result.get('score', 0) * 100:.0f}%</td>
                    <td>{test_result.get('message', '')}</td>
                </tr>
                """

            suites_html += f"""
            <div class="suite {suite_status}">
                <div class="suite-header">
                    <h3>{suite_icon} {suite.get('suite_name', 'Unknown')}</h3>
                    <div class="suite-stats">
                        <span>Tests: {suite.get('total_tests', 0)}</span>
                        <span class="pass">Passed: {suite.get('passed', 0)}</span>
                        <span class="fail">Failed: {suite.get('failed', 0)}</span>
                        <span>Duration: {suite.get('duration', 0):.2f}s</span>
                    </div>
                </div>
                <table class="test-table">
                    <thead>
                        <tr>
                            <th>Test</th>
                            <th>Status</th>
                            <th>Duration</th>
                            <th>Score</th>
                            <th>Message</th>
                        </tr>
                    </thead>
                    <tbody>{tests_html}</tbody>
                </table>
            </div>
            """

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AgentTestPilot Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #f5f7fa;
            color: #333;
            line-height: 1.6;
        }}
        .container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            border-radius: 12px;
            margin-bottom: 30px;
            text-align: center;
        }}
        .header h1 {{ font-size: 2.5em; margin-bottom: 10px; }}
        .header p {{ opacity: 0.9; }}
        .summary {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }}
        .summary-card {{
            background: white;
            padding: 25px;
            border-radius: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            text-align: center;
        }}
        .summary-card .number {{
            font-size: 2.5em;
            font-weight: bold;
            color: #667eea;
        }}
        .summary-card .label {{ color: #666; font-size: 0.9em; margin-top: 5px; }}
        .summary-card.pass .number {{ color: #28a745; }}
        .summary-card.fail .number {{ color: #dc3545; }}
        .summary-card.error .number {{ color: #ffc107; }}
        .success-rate {{
            background: white;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            margin-bottom: 30px;
            text-align: center;
        }}
        .rate-circle {{
            width: 150px;
            height: 150px;
            border-radius: 50%;
            border: 8px solid {rate_color};
            display: inline-flex;
            align-items: center;
            justify-content: center;
            font-size: 2em;
            font-weight: bold;
            color: {rate_color};
            margin-bottom: 15px;
        }}
        .suite {{
            background: white;
            border-radius: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            margin-bottom: 20px;
            overflow: hidden;
        }}
        .suite-header {{
            padding: 20px 25px;
            background: #f8f9fa;
            border-bottom: 1px solid #e9ecef;
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 10px;
        }}
        .suite-header h3 {{ color: #333; }}
        .suite-stats {{ display: flex; gap: 20px; font-size: 0.9em; }}
        .suite-stats span {{ color: #666; }}
        .suite-stats .pass {{ color: #28a745; font-weight: bold; }}
        .suite-stats .fail {{ color: #dc3545; font-weight: bold; }}
        .test-table {{ width: 100%; border-collapse: collapse; }}
        .test-table th {{
            padding: 15px 25px;
            text-align: left;
            background: #f8f9fa;
            font-weight: 600;
            color: #555;
            border-bottom: 1px solid #e9ecef;
        }}
        .test-table td {{
            padding: 15px 25px;
            border-bottom: 1px solid #f0f0f0;
        }}
        .test-table tr:hover {{ background: #f8f9fa; }}
        .test-table tr.passed {{ border-left: 4px solid #28a745; }}
        .test-table tr.failed {{ border-left: 4px solid #dc3545; }}
        .test-table tr.error {{ border-left: 4px solid #ffc107; }}
        .test-table tr.skipped {{ border-left: 4px solid #6c757d; }}
        .badge {{
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 0.75em;
            font-weight: 600;
            text-transform: uppercase;
        }}
        .badge.passed {{ background: #d4edda; color: #155724; }}
        .badge.failed {{ background: #f8d7da; color: #721c24; }}
        .badge.error {{ background: #fff3cd; color: #856404; }}
        .badge.skipped {{ background: #e2e3e5; color: #383d41; }}
        .footer {{
            text-align: center;
            padding: 30px;
            color: #666;
            font-size: 0.9em;
        }}
        .footer a {{ color: #667eea; text-decoration: none; }}
        @media (max-width: 768px) {{
            .header h1 {{ font-size: 1.8em; }}
            .suite-header {{ flex-direction: column; align-items: flex-start; }}
            .suite-stats {{ flex-wrap: wrap; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🧪 AgentTestPilot</h1>
            <p>AI Agent Automated Testing & Behavior Validation Report</p>
            <p style="margin-top:10px;opacity:0.8;">{data.get('timestamp', '')}</p>
        </div>

        <div class="summary">
            <div class="summary-card">
                <div class="number">{total}</div>
                <div class="label">Total Tests</div>
            </div>
            <div class="summary-card pass">
                <div class="number">{passed}</div>
                <div class="label">Passed</div>
            </div>
            <div class="summary-card fail">
                <div class="number">{failed}</div>
                <div class="label">Failed</div>
            </div>
            <div class="summary-card error">
                <div class="number">{errors}</div>
                <div class="label">Errors</div>
            </div>
            <div class="summary-card">
                <div class="number">{skipped}</div>
                <div class="label">Skipped</div>
            </div>
        </div>

        <div class="success-rate">
            <div class="rate-circle">{rate:.0f}%</div>
            <h3>Overall Success Rate</h3>
            <p>Total Duration: {data.get('total_duration', 0):.2f}s</p>
        </div>

        <h2 style="margin-bottom:20px;">📁 Suite Details</h2>
        {suites_html}

        <div class="footer">
            <p>Generated by <a href="https://github.com/gitstq/AgentTestPilot" target="_blank">AgentTestPilot</a></p>
        </div>
    </div>
</body>
</html>"""
